//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_MovieTicketBookingApp.Master_Pages {
    
    
    public partial class MasterPage_Login_No {
        
        /// <summary>
        /// SUB_HEAD_LOGIN_NO_CONTENTPLACEHOLDER control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder SUB_HEAD_LOGIN_NO_CONTENTPLACEHOLDER;
        
        /// <summary>
        /// SMDS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SiteMapDataSource SMDS1;
        
        /// <summary>
        /// MAIN_MENU control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu MAIN_MENU;
        
        /// <summary>
        /// SUB_BODY_LOGIN_NO_CONTENTPLACEHOLDER control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder SUB_BODY_LOGIN_NO_CONTENTPLACEHOLDER;
    }
}
